name: Apollo Build Pipeline

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
    secrets:
      NODE_AUTH_TOKEN:
        required: true
      HARBOR_AUTH_USERNAME:
        required: true
      HARBOR_AUTH_SECRET:
        required: true
      GOOGLE_AUTH_TOKEN:
        required: true
      APOLLO_KEY:
        required: true
      DOPPLER_KEY_DEV:
        required: true
      DOPPLER_KEY_PRD:
        required: true

jobs:
  build:
    uses: dashboardlabs/common-actions/.github/workflows/docker-build.yml@develop
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      HARBOR_AUTH_USERNAME: ${{ secrets.HARBOR_AUTH_USERNAME }}
      HARBOR_AUTH_SECRET: ${{ secrets.HARBOR_AUTH_SECRET }}
  deploy_gke_dashlabs_private_dev:
    name: Deploy Docker Image (Dev - GKE Dashlabs Private Cluster)
    needs: build
    if: github.ref == 'refs/heads/develop'
    uses: dashboardlabs/common-actions/.github/workflows/kube-deploy.yml@develop
    with:
      namespace: dashlabs-dev
      node-selector: "cloud.google.com/gke-preemptible: \"true\" "
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      GOOGLE_AUTH_TOKEN: ${{ secrets.GOOGLE_AUTH_TOKEN }}
      DOPPLER_KEY: ${{ secrets.DOPPLER_KEY_DEV }}
  deploy_gke_dashlabs_private_delta:
    name: Deploy Docker Image (Delta - GKE Dashlabs Private Cluster)
    needs: build
    if: github.ref == 'refs/heads/delta'
    uses: dashboardlabs/common-actions/.github/workflows/kube-deploy.yml@develop
    with:
      namespace: dashlabs-delta
      node-selector: "cloud.google.com/gke-preemptible: \"true\" "
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      GOOGLE_AUTH_TOKEN: ${{ secrets.GOOGLE_AUTH_TOKEN }}
      DOPPLER_KEY: ${{ secrets.DOPPLER_KEY_DEV }}
  deploy_gke_dashlabs_private_prod:
    name: Deploy Docker Image (Prod - GKE Dashlabs Private Cluster)
    needs: build
    if: github.ref == 'refs/heads/master'
    uses: dashboardlabs/common-actions/.github/workflows/kube-deploy.yml@develop
    with:
      namespace: dashlabs-prod
      node-selector: ""
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      GOOGLE_AUTH_TOKEN: ${{ secrets.GOOGLE_AUTH_TOKEN }}
      DOPPLER_KEY: ${{ secrets.DOPPLER_KEY_PRD }}
  update_gateway_dev:
    name: Update Gateway Server (Dev)
    needs: deploy_gke_dashlabs_private_dev
    uses: dashboardlabs/common-actions/.github/workflows/update-apollo-gateway.yml@develop
    with:
      environment: develop
      service: ${{ inputs.service-name }}
      endpoint: http://${{ inputs.service-name }}.dashlabs-dev.svc.cluster.local/
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
  update_gateway_delta:
    name: Update Gateway Server (Delta)
    needs: deploy_gke_dashlabs_private_delta
    uses: dashboardlabs/common-actions/.github/workflows/update-apollo-gateway.yml@develop
    with:
      environment: delta
      service: ${{ inputs.service-name }}
      endpoint: http://${{ inputs.service-name }}.dashlabs-delta.svc.cluster.local/
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
  update_gateway_prod:
    name: Update Gateway Server (Prod)
    needs: deploy_gke_dashlabs_private_prod
    uses: dashboardlabs/common-actions/.github/workflows/update-apollo-gateway.yml@develop
    with:
      environment: master
      service: ${{ inputs.service-name }}
      endpoint: http://${{ inputs.service-name }}.dashlabs-prod.svc.cluster.local/
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
