name: Docker Build

on:
  workflow_call:
    secrets:
      HARBOR_AUTH_USERNAME:
        required: true
      HARBOR_AUTH_SECRET:
        required: true
      NODE_AUTH_TOKEN:
        required: true

jobs:
  build:
    name: Build Docker Image
    runs-on: [self-hosted, gcp-dashlabs-private-network]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        registry: registry.dashlabs.xyz
        username: ${{ secrets.HARBOR_AUTH_USERNAME }}
        password: ${{ secrets.HARBOR_AUTH_SECRET }}

    - name: Set Docker Image Version
      run: echo "VERSION=$(echo "${{ github.ref }}" | grep "develop" > /dev/null && echo "develop" || (echo "${{ github.ref }}" | grep "delta" > /dev/null && echo "delta" || echo "latest"))" >> $GITHUB_ENV

    - name: Get Repository Name
      run: echo "REPO_NAME=$(echo "${{ github.repository }}" | sed -e 's,.*/\(.*\),\1,')" >> $GITHUB_ENV

    - name: Build and Push
      uses: docker/build-push-action@v2
      id: build-docker-image
      with:
        context: .
        push: true
        tags: registry.dashlabs.xyz/dashlabsai/${{ env.REPO_NAME }}:${{ env.VERSION }}
        build-args: |
          NPM_TOKEN="${{ secrets.NODE_AUTH_TOKEN }}"

    - name: Save Docker Digest
      run: echo "${{ steps.build-docker-image.outputs.digest }}" > digest.txt

    - name: Upload Docker Digest
      uses: actions/upload-artifact@v2
      with:
        name: digest
        path: digest.txt
