name: NextJS Build Pipeline

on:
  workflow_call:
    secrets:
      NODE_AUTH_TOKEN:
        required: true
      HARBOR_AUTH_USERNAME:
        required: true
      HARBOR_AUTH_SECRET:
        required: true
      GOOGLE_AUTH_TOKEN:
        required: true
      CLOUDFLARE_ZONE:
        required: true
      CLOUDFLARE_TOKEN:
        required: true

jobs:
  build_next:
    uses: dashboardlabs/common-actions/.github/workflows/nextjs-build.yml@develop
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
  build:
    uses: dashboardlabs/common-actions/.github/workflows/docker-build.yml@develop
    needs: build_next
    if: ${{ contains(github.ref, 'develop') || contains(github.ref, 'delta') || contains(github.ref, 'master') }}
    with:
      nextjs-project: true
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      HARBOR_AUTH_USERNAME: ${{ secrets.HARBOR_AUTH_USERNAME }}
      HARBOR_AUTH_SECRET: ${{ secrets.HARBOR_AUTH_SECRET }}
  deploy_gke_dashlabs_private_dev:
    name: Deploy Docker Image (Dev - GKE Dashlabs Private Cluster)
    needs: build
    if: github.ref == 'refs/heads/develop'
    uses: dashboardlabs/common-actions/.github/workflows/kube-deploy.yml@develop
    with:
      namespace: dashlabs-dev
      node-selector: "cloud.google.com/gke-preemptible: \"true\" "
      doppler: false
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      GOOGLE_AUTH_TOKEN: ${{ secrets.GOOGLE_AUTH_TOKEN }}
  deploy_gke_dashlabs_private_delta:
    name: Deploy Docker Image (Delta - GKE Dashlabs Private Cluster)
    needs: build
    if: github.ref == 'refs/heads/delta'
    uses: dashboardlabs/common-actions/.github/workflows/kube-deploy.yml@develop
    with:
      namespace: dashlabs-delta
      node-selector: "cloud.google.com/gke-preemptible: \"true\" "
      doppler: false
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      GOOGLE_AUTH_TOKEN: ${{ secrets.GOOGLE_AUTH_TOKEN }}
  deploy_gke_dashlabs_private_prod:
    name: Deploy Docker Image (Prod - GKE Dashlabs Private Cluster)
    needs: build
    if: github.ref == 'refs/heads/master'
    uses: dashboardlabs/common-actions/.github/workflows/kube-deploy.yml@develop
    with:
      namespace: dashlabs-prod
      node-selector: ""
      doppler: false
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      GOOGLE_AUTH_TOKEN: ${{ secrets.GOOGLE_AUTH_TOKEN }}
  clear_google_cdn_cache_prod:
    name: Clear Google Cloud CDN Cache (Prod)
    runs-on: ubuntu-latest
    needs: deploy_gke_dashlabs_private_prod
    steps:
    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GOOGLE_AUTH_TOKEN }}
        project_id: dashlabs
    - name: Invalidate Cache
      run: |-
        gcloud compute url-maps invalidate-cdn-cache k8s2-um-t59hwxf0-dashlabs-prod-dashlabs-ingress-neg-1x90av7v --path "/*"
  clear_cf_cache:
    name: Clear Cloudflare Cache
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [deploy_gke_dashlabs_private_dev, deploy_gke_dashlabs_private_delta, clear_google_cdn_cache_prod]
    steps:
    - name: Purge cache
      uses: jakejarvis/cloudflare-purge-action@master
      env:
        CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
        CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
