name: NPM Publish

on:
  workflow_call:
    inputs:
      use-gh-app:
        required: false
        default: false
        type: boolean
      move-dir:
        required: false
        default: true
        type: boolean
      build:
        required: false
        default: true
        type: boolean
    secrets:
      NODE_AUTH_TOKEN:
        required: true
      GH_APP_ID:
        required: false
      GH_APP_PRIVATE_KEY:
        required: false

jobs:
  build:
    name: Publish NPM Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          ref: ${{ github.event.release.target_commitish }}
          fetch-depth: 0 
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: https://npm.pkg.github.com/
          scope: '@dashboardlabs'
      - run: git config user.name github-actions
      - run: git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - run: npm run build
        if: inputs.build
      - run: mv dist/* .
        if: inputs.move-dir
      - run: npm version ${{ github.event.release.tag_name || 'patch' }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: git push
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Token
        id: token
        uses: getsentry/action-github-app-token@v1
        if: inputs.use-gh-app
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - name: Bumping
        uses: derberg/npm-dependency-manager-for-your-github-org@v3
        if: inputs.use-gh-app
        with:
          github_token: ${{ steps.token.outputs.token }}
          committer_username: x-access-token
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
