name: NPM Publish

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
    secrets:
      GH_APP_ID:
        required: true
      GH_APP_PRIVATE_KEY:
        required: true

jobs:
  build:
    name: Publish NPM Package
    runs-on: ubuntu-latest
    steps:
      - name: Get Token
        id: token
        uses: getsentry/action-github-app-token@v1
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v2
        with: 
          ref: ${{ inputs.ref }}
          fetch-depth: 0 
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
          cache: 'npm'
          registry-url: https://npm.pkg.github.com/
          scope: '@dashboardlabs'
      - run: git config user.name github-actions
      - run: git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ steps.token.outputs.token }}
      - run: npm run build
      - run: mv dist/* .
      - run: npm version ${{ github.event.release.tag_name }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ steps.token.outputs.token }}
      - run: git push
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
