name: NPM Test

on:
  workflow_call:
    secrets:
      NODE_AUTH_TOKEN:
        required: true

jobs:
  test:
    name: Run NPM Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb_version: ["4.4.8", "5.0.2"]
      fail-fast: false
    env:
      MONGOMS_VERSION: ${{ matrix.mongodb_version }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
        registry-url: https://npm.pkg.github.com/
        scope: '@dashboardlabs'
    - run: npm ci
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
    - run: npm run test
      env:
        NODE_OPTIONS: --max-old-space-size=8192
    - uses: romeovs/lcov-reporter-action@v0.2.16
      with:
        lcov-file: ./coverage/lcov.info
